- name: Install Docker and run Nginx
  hosts: web
  become: true

  tasks:
    - name: Enable and install Docker from amazon-linux-extras
      shell: |
        amazon-linux-extras enable docker
        yum clean metadata
        yum install -y docker
      args:
        executable: /bin/bash

    - name: Start and enable Docker
      systemd:
        name: docker
        state: started
        enabled: true

    - name: Install Docker Compose (standalone)
      get_url:
        url: https://github.com/docker/compose/releases/download/v2.24.7/docker-compose-linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: '0755'

    - name: Pull nginx image
      docker_image:
        name: nginx
        source: pull

    - name: Create Docker Compose file
      copy:
        dest: /home/ec2-user/docker-compose.yml
        content: |
          version: '3'
          services:
            nginx:
              image: nginx
              ports:
                - "80:80"

    - name: Run Nginx with Docker Compose
      shell: /usr/local/bin/docker-compose up -d
      args:
        chdir: /home/ec2-user/
