---
- name: Setup Jenkins master with existing nginx reverse proxy
  hosts: jenkins
  become: yes
  tasks:
    - name: Enable Amazon Corretto 17
      command: amazon-linux-extras enable corretto17
      register: enable_java
      changed_when: "'enabled' in enable_java.stdout"

    - name: Clean yum cache
      command: yum clean metadata
      when: enable_java is changed

    - name: Install Java 17 Amazon Corretto
      yum:
        name: java-17-amazon-corretto-devel
        state: present

    - name: Add Jenkins repo key
      rpm_key:
        state: present
        key: https://pkg.jenkins.io/redhat-stable/jenkins.io.key

    - name: Add Jenkins repo
      yum_repository:
        name: jenkins
        description: Jenkins repo
        baseurl: https://pkg.jenkins.io/redhat-stable/
        gpgcheck: yes
        gpgkey: https://pkg.jenkins.io/redhat-stable/jenkins.io.key

    - name: Install Jenkins
      yum:
        name: jenkins
        state: present
        update_cache: yes

    - name: Enable and start Jenkins
      systemd:
        name: jenkins
        state: started
        enabled: yes

    - name: Configure nginx as reverse proxy for Jenkins
      copy:
        dest: /etc/nginx/conf.d/jenkins.conf
        content: |
          server {
              listen 80;
              location / {
                  proxy_pass http://localhost:8080;
                  proxy_set_header Host $host;
                  proxy_set_header X-Real-IP $remote_addr;
                  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                  proxy_set_header X-Forwarded-Proto $scheme;
              }
          }

    - name: Remove default nginx config to avoid conflicts
      file:
        path: /etc/nginx/conf.d/default.conf
        state: absent

    - name: Restart nginx
      systemd:
        name: nginx
        state: restarted
        enabled: yes
