services:
  app:
    build: .
    container_name: app
    expose:
      - "5000"
    volumes:
      - ./students.csv:/app/students.csv  
    networks:
      - appnet

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - appnet

networks:
  appnet:
    driver: bridge
