Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"

  config.vm.network "public_network"

  config.vm.provision "shell", inline: <<-SHELL
    sudo apt update
    sudo apt install -y nginx
    sudo sed -i 's/listen 80 default_server;/listen 82 default_server;/g' /etc/nginx/sites-available/default
    sudo sed -i 's/listen \\[::\\]:80 default_server;/listen \\[::\\]:82 default_server;/g' /etc/nginx/sites-available/default
    sudo systemctl restart nginx
  SHELL
end
